name: fake-reviews-detector
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - nltk
  - pyyaml
  - pip
  - pip:
      - kagglehub
      - pytest
