name: fake-review-detector
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - nltk
  - tqdm
  - joblib
  - click
  - pyyaml
  - pip
  - pip:
    - kaggle

