app:
  title: "Fake-Reviews-Detecter"
  geometry: "800x600"
  background: "#f0f0f0"

styles:
  button:
    font: "Arial 10"
    padding: 5
  label:
    font: "Arial 10"
    background: "#f0f0f0"

files:
  default_train_dir: "data/train"
  default_predict_dir: "data/predict"
  allowed_extensions: ["csv", "txt"]

ui_text:
  main:
    load_data: "Загрузка данных"
    model_training: "Обучение модели"
    prediction: "Предсказание"
  buttons:
    browse: "Обзор"
    train: "Обучить модель"
    predict: "Сделать предсказание"
  labels:
    train_file: "Файл для обучения:"
    input_text: "Введите строку для предсказания:"
    input_file: "Или загрузите файл для предсказания:"
    results: "Результаты:"
  status:
    ready: "Готов к работе"
    loading_data: "Чтение данных..."
    splitting_data: "Разделение данных..."
    training: "Обучение модели..."
    evaluating: "Оценка модели..."
    trained: "Модель обучена. Точность: {accuracy:.2f}"
