dataset_path: data/processed/data.csv
model_path: data/model/model.pkl
vectorizer_path: data/model/vectorizer.pkl

dataset:
  columns:
    review: text_
    label: label
  values:
    good: OR
    bad: CG

preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_stopwords: true
  stemming: false
  lemmatization: true
  max_features: 10000
  ngram_range: [1, 2]

vectorizer:
  type: tfidf
  max_features: 10000
  ngram_range: [1, 2]

model:
  type: logistic_regression
  hyperparameters:
    C: 1.0
    max_iter: 1000
    solver: lbfgs

training:
  test_size: 0.2
  random_state: 42
  stratify: true
